### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by booming** [kamildrazkiewicz/go-flow#1]
In your example, when f2 (same will happen when f3, f4 return error) returns an error, the program will crash. for then channel f1 was closed already.

**Comment by booming** [comment]
I Noticed you tried to fix the bug, but I don't think it will work out, under multi goroutine conditions some channel still might be closed more than once unless you lock the close procedure. I don't even think lock close procedure is a good idea, the purpose of closing all the channels is that you just want all waiting goroutines to quit, why not send some special return value to the results channel (or even declare a bunch of channels for passing deps excute success/failure) and let waiting goroutines quit respectively then close all channels after that (eg. in the do() func before after wait for all)?

**Comment by kamildrazkiewicz** [comment]
Thanks for your feedback.

I used `atomic.Value` to store information about the current state of channel (if it's closed). Atomic value guarantee that if state has changed, other goroutines will load them with this state. So, in my opinion there is no an option panic here. 

On the question of use quit channel, of course that will works but I think it's a more complicated way.

If I'm wrong, I will be pleased to see some example with failure.
