### ISSUE TITLE
Question abour : closed  atomic.Value 

### ISSUE THREAD

**Issue by ledao** [kamildrazkiewicz/go-flow#2]
Hi, 
I am confused about "closed  atomic.Value" in struct flowStruct.
fs.closed.Load() is nil, which != ture or false, so the code in the if branch can never be executed.
Is this a bug?

**Comment by kamildrazkiewicz** [comment]
Fixed with [a316c03](https://github.com/kamildrazkiewicz/go-flow/commit/a316c0311128f1650e2411c65487c8fd20423239).
